# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- development

pool:
  vmImage: ubuntu-latest

parameters:
  - name: environmentName
    type: string
    default: windows-latest

stages:
 - stage: "Build"
   jobs:
      - job: Build
        steps:
        - task: NodeTool@0
          displayName: ${{parameters.environmentName}}
          inputs:
            versionSource: 'spec'
            versionSpec: '16.x'
        
        - task: Npm@1
          inputs:
            command: 'install'
        
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build'
        
        - task: CopyFiles@2
          displayName: CopyFile
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/build'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)/build'
        
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifact: 'drop'
            publishLocation: 'pipeline'
          displayName: 'Publish Pipeline Artifact' 


 - stage: Deploy
   displayName: DeployDev
   jobs:
    - deployment: DownloadArtiface
      environment: 'Dev-environment'
      workspace:
        clean: all
      strategy:
       runOnce:
        deploy:
          steps:
          - download: none
          - task: DownloadPipelineArtifact@2
            displayName: Pipeline artifact
            inputs:
                buildType: current
                artifactName: drop
                targetPath: $(Build.SourcesDirectory)
    - job: Deploy
      steps:
        - task: AzureRmWebAppDeployment@5
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Free Trial(1280e451-1849-47f6-949e-8bcc6acd2598)'
            appType: 'webAppLinux'
            WebAppName: 'webapp1234'
            packageForLinux: '$(Build.SourcesDirectory)/build'
            DeploymentTypeLinux: 'oneDeploy'
        
        
        



